### PR TITLE
Run more checks in CI

### PR DESCRIPTION
**Pull request by vbrandl**
The following checks were added to the CI pipeline:

* formatting check (unformatted files cause the pipeline to fail)
* clippy lints (the [clippy](https://github.com/rust-lang/rust-clippy/) linter is executed and fails if lints are found)
* Run tests on Linux, Windows and Mac OS

I gues 3 to 4 minutes is still OK for the pipeline?

### CODE REVIEW

**Review by mstruebing — COMMENTED** [review]
Would be cool to still have the build and the "self check" which is currently missing, right?
Otherwise, the runtime is okay I would say.

**Comment by vbrandl** [comment]
The self check has been implemented in 83e86f6.

I don't know why the formatting pipeline failed once and succeeded the other time, but I think this might just be a bug in GH Actions.

**Comment by mstruebing** [comment]
It seems there was something unformatted in master, a rebase made that clear.
The windows run is still failing, I have no idea currently.

**Comment by vbrandl** [comment]
Looks like on Windows, extracting the release archive fails. This is not an issue with the CI pipeline but a bug in the code that has to be investigated.

If there is nothing else, I would merge this PR and open an issue for the problem.

Edit: Here is the issue: https://github.com/editorconfig-checker/editorconfig-checker.rust/issues/12

**Review by mstruebing — APPROVED** [review]
Yep, I'm fine with this.

**Pull request merged**
